exports.EMPTY_FILE = 'EMPTY_FILE';
exports.EMPTY_TITLE = 'EMPTY_TITLE';
exports.EMPTY_TYPE = 'EMPTY_TYPE';
exports.INVALID_TYPE = 'INVALID_TYPE';
exports.UNAUTHORIZED = 'UNAUTHORIZED';
exports.ALGOLIA_ERROR = 'ALGOLIA_ERROR';
exports.GCP_ERROR = 'GCP_ERROR';
